# Generated by Django 4.0.4 on 2022-08-11 17:23

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('budget_deducted_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.budget')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='income_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetapp.income'),
        ),
    ]
