# Generated by Django 4.0.4 on 2022-08-20 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0004_alter_expense_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetapp.appuser'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetapp.appuser'),
        ),
        migrations.AddField(
            model_name='income',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgetapp.appuser'),
        ),
    ]
