# Generated by Django 4.0.4 on 2022-11-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0005_budget_created_by_expense_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='initial_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
