# Generated by Django 4.0.4 on 2022-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0006_budget_initial_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='initial_income',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
