# Generated by Django 4.0.4 on 2022-11-28 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetapp', '0007_income_initial_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='income',
            name='period',
            field=models.CharField(max_length=100000),
        ),
    ]
